name: FunctionalClans
version: '${project.version}'
main: ru.oshifugo.functionalclans.FunctionalClans
api-version: 1.13
authors: [ OshiFugo ]
description: I'm in charge of the clan system. Only shhh....

commands:
  clan:
    description: Basic plugin commands
    usage: </command>
    aliases:
      - c
  fc:
    description: Admin plugin management commands
    usage: </command>
